# Generated by Django 5.0.1 on 2024-02-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='email',
            new_name='email_address',
        ),
    ]
